// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import "./globals.css";
import "./style/home.css";
import "./style/nav.css";
import "./style/about.css";
import "./style/blog.css";
import "./style/blogNav.css";
import "./style/btn-small.css";
import "./style/button.css";
import "./style/buttonI.css";
import "./style/carousal.css";
import "./style/caseStudy.css";
import "./style/casrbtn.css";
import "./style/ConnectModal.css";
import "./style/contact.css";
import "./style/cs.css";
import "./style/DotDrid.css";
import "./style/faq.css";
import "./style/footer.css";
import "./style/loader.css";
import "./style/loop.css";
import "./style/module.css";
import "./style/mvp.css";
import "./style/normsmallbtn.css";
import "./style/note.css";
import "./style/notFound.css";
import "./style/pageTrans.css";
import "./style/Project.css";
import "./style/scrollreveal.css";
import "./style/services.css";
import "./style/splitText.css";
import "./style/spotlight.css";
import "./style/test.css";
import "./style/threecard.css";
import "./style/uiux.css";
import "./style/animation.css";

export const metadata: Metadata = {
  title: "Strix Production",
  description: "End-to-End SaaS Development Company",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}